#!/usr/bin/bash

function dbg {
    echo $@
}


BOLD=$'\e[1;31m'
RESET=$'\e[0m'

export DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $DIR/.lib/utils.sh
export WORLD=$DIR/world
export CHEST=$WORLD/cottage/
CAVE=$FOREST/cave
DESERT=$WORLD/desert
CASTLE=$WORLD/castle
LIBRARY=$CASTLE/library
CATACOMBS=$LIBRARY/catacombs
RUINS=$DESERT/ruins

declare -A ITEMS
ITEMS=(
    [cave]=0
    [bear_in_chest]=0
)
declare -A POSSIBLE_POINTS
declare -a SCORING_FUNCTIONS

export ITEMS
export POSSIBLE_POINTS
export SCORING_FUNCTIONS

GAME_OVER=0
BEAR_IN_CHEST=0
WRONG_WATERINGHOLE=0



function load_all_scoring {
    # for resource_dir in $(find $WORLD -type d -name __pta_resources 2>/dev/null); do
    #     for scorer in "$resource_dir"/*score.sh; do
    #         if [[ $scorer != "$resource_dir"/'*score.sh' ]]; then
    #             source "$scorer"
    #         fi
    #     done
    # done
    # local script
    # for script in "$SCORE_DIR"/*; do
    #     if [[ -e "$script" ]]; then 
    #         source "$script"
    #     fi
    # done
    __pta_load_all "$SCORE_DIR"
}

function score_all {
    for scoring_function in "${SCORING_FUNCTIONS[@]}"; do
        "$scoring_function"
    done
}

function print_bear_in_chest {
    cat << EOF

\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/
You've put a bear in your treasure chest!
It eats all your points: -$(calculate_total) Points!
And then it eats you!

                        ${BOLD}GAME OVER${RESET}

Type ${BOLD}exit${RESET} and press ${BOLD}[Enter]${RESET}
/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\/\\
EOF
}

function print_wrong_wateringhole {
    cat << EOF
    
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
You wasted precious time touching watering holes that
only SEEMED to be there. You died of thirst, and the husk
of your body was devoured by the desert.

                        ${BOLD}GAME OVER${RESET}

Type ${BOLD}exit${RESET} and press ${BOLD}[Enter]${RESET}
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
EOF
}

function print_you_win {
    cat << EOF

                          🎊 YOU WIN!!! 🎊

You are the greatest terminal jockey in all the land! Congratulations!

Type ${BOLD}exit${RESET} and press ${BOLD}[Enter]${RESET}

EOF
}

function calculate_total {
    declare -i TOTAL=0
    for p in "${ITEMS[@]}"; do
        TOTAL=$((TOTAL + p))
    done
    echo $TOTAL
}

function print_score {
    score_all
    echo ""
    echo "This program will tell you how you have done."
    echo "============================================="
    echo "How did you do for the first steps?"
    [[ ${ITEMS[cottage_chest]} -ne 0 ]] && echo "Treasure Chest Created: ${ITEMS[cottage_chest]} Point"
    [[ ${ITEMS[cottage_name]} -ne 0 ]] && echo "Name file created: ${ITEMS[cottage_name]} Point"
    [[ ${ITEMS[cottage_chest]} -ne 0 && ${ITEMS[cottage_name]} -ne 0 ]] || echo "COTTAGE: Unfinished"
    echo ""
    echo "Now, how about the rest?"
    echo "========================"
    [[ ${ITEMS[castle]} -ne 0 ]] && echo " CASTLE: ${ITEMS[castle]} Points" || echo " CASTLE: Unfinished"
    [[ ${ITEMS[library]} -ne 0 ]] && echo "LIBRARY: ${ITEMS[library]} Points" || echo "LIBRARY: Unfinished"
    [[ ${ITEMS[desert]} -ne 0 ]] && echo " DESERT: ${ITEMS[desert]} Points" || echo " DESERT: Unfinished"
    [[ ${ITEMS[ruins]} -ne 0 ]] && echo "  RUINS: ${ITEMS[ruins]} Points" || echo "  RUINS: Unfinished"
    [[ ${ITEMS[forest]} -ne 0 ]] && echo " FOREST Bonus!: ${ITEMS[forest]} Points"
    [[ ${ITEMS[cave]} -ne 0 ]] && echo "   CAVE: ${ITEMS[cave]} Points" || echo "   CAVE: Unfinished"
    [[ ${ITEMS[glen]} -ne 0 ]] && echo "HIDDEN GLEN: ${ITEMS[glen]} Points" || echo "...Hmmm...Did you search everywhere?"
    if [[ $GAME_OVER -eq 0 ]]; then 
        local TOTAL=$(calculate_total)
        echo "==================="
        echo "TOTAL SCORE: $TOTAL"
        echo ""
        if [[ $TOTAL -ge 32 ]]; then
            print_you_win
            exit
        fi
    else
        if [[ $BEAR_IN_CHEST -ne 0 ]]; then  
            calculate_total
            print_bear_in_chest
            exit
        elif [[ $WRONG_WATERINGHOLE -ne 0 ]]; then
            calculate_total
            print_wrong_wateringhole
            exit
        fi
    fi
}

load_all_scoring
score_all
print_score
